# Compliance Baseline: CIS macOS Benchmark — Level 1
# macOS 26 (26.0+)
# mSCP branch: tahoe  revision: rev3.0
# Generated by scripts/generate_tf_compliance.py — DO NOT EDIT DIRECTLY

locals {
  # All rules for this baseline (id, title, severity)
  all_rules = [
    {
      "id" : "audit_acls_files_configure",
      "title" : "Configure Audit Log Files to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_acls_folders_configure",
      "title" : "Configure Audit Log Folder to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_auditd_enabled",
      "title" : "Enable Security Auditing",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_acls_configure",
      "title" : "Configure Audit_Control to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_group_configure",
      "title" : "Configure Audit_Control Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_mode_configure",
      "title" : "Configure Audit_Control Owner to Mode 440 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_owner_configure",
      "title" : "Configure Audit_Control Owner to Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_group_configure",
      "title" : "Configure Audit Log Files Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_mode_configure",
      "title" : "Configure Audit Log Files to Mode 440 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_owner_configure",
      "title" : "Configure Audit Log Files to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_group_configure",
      "title" : "Configure Audit Log Folders Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_owner_configure",
      "title" : "Configure Audit Log Folders to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_folders_mode_configure",
      "title" : "Configure Audit Log Folders to Mode 700 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_retention_configure",
      "title" : "Configure Audit Retention to $ODV",
      "severity" : "low"
    },
    {
      "id" : "os_airdrop_disable",
      "title" : "Disable AirDrop",
      "severity" : "medium"
    },
    {
      "id" : "os_anti_virus_installed",
      "title" : "Must Use an Approved Antivirus Program",
      "severity" : "high"
    },
    {
      "id" : "os_authenticated_root_enable",
      "title" : "Enable Authenticated Root",
      "severity" : "medium"
    },
    {
      "id" : "os_config_data_install_enforce",
      "title" : "Enforce Installation of XProtect Remediator and Gatekeeper Updates Automatically",
      "severity" : "medium"
    },
    {
      "id" : "os_external_apfs_hfs_volumes_encrypted",
      "title" : "Ensure All APFS and HFS+ External User Storage Volumes Are Encrypted",
      "severity" : "medium"
    },
    {
      "id" : "os_gatekeeper_enable",
      "title" : "Enable Gatekeeper",
      "severity" : "high"
    },
    {
      "id" : "os_guest_folder_removed",
      "title" : "Remove Guest Folder if Present",
      "severity" : "medium"
    },
    {
      "id" : "os_home_folders_secure",
      "title" : "Secure User's Home Folders",
      "severity" : "medium"
    },
    {
      "id" : "os_httpd_disable",
      "title" : "Disable the Built-in Web Server",
      "severity" : "medium"
    },
    {
      "id" : "os_install_log_retention_configure",
      "title" : "Configure Install.log Retention to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_internal_apfs_volumes_encrypted",
      "title" : "Ensure All Internal User Storage APFS Volumes Are Encrypted",
      "severity" : "medium"
    },
    {
      "id" : "os_mail_summary_disable",
      "title" : "Disable Apple Intelligence Mail Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_mobile_file_integrity_enable",
      "title" : "Enable Apple Mobile File Integrity",
      "severity" : "medium"
    },
    {
      "id" : "os_nfsd_disable",
      "title" : "Disable Network File System Service",
      "severity" : "medium"
    },
    {
      "id" : "os_notes_transcription_disable",
      "title" : "Disable Apple Intelligence Notes Transcription",
      "severity" : "medium"
    },
    {
      "id" : "os_notes_transcription_summary_disable",
      "title" : "Disable Apple Intelligence Notes Transcription Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_on_device_dictation_enforce",
      "title" : "Enforce On Device Dictation",
      "severity" : "medium"
    },
    {
      "id" : "os_password_hint_remove",
      "title" : "Remove Password Hint From User Accounts",
      "severity" : "medium"
    },
    {
      "id" : "os_power_nap_disable",
      "title" : "Disable Power Nap",
      "severity" : "medium"
    },
    {
      "id" : "os_root_disable",
      "title" : "Disable Root Login",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_advertising_privacy_protection_enable",
      "title" : "Ensure Advertising Privacy Protection in Safari Is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_open_safe_downloads_disable",
      "title" : "Disable Automatic Opening of Safe Files in Safari",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_prevent_cross-site_tracking_enable",
      "title" : "Ensure Prevent Cross-site Tracking in Safari Is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_show_full_website_address_enable",
      "title" : "Ensure Show Full Website Address in Safari Is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_show_status_bar_enabled",
      "title" : "Ensure Show Safari shows the Status Bar is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_warn_fraudulent_website_enable",
      "title" : "Ensure Warn When Visiting A Fraudulent Website in Safari Is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_sip_enable",
      "title" : "Ensure System Integrity Protection is Enabled",
      "severity" : "high"
    },
    {
      "id" : "os_software_update_app_update_enforce",
      "title" : "Enforce Software Update App Update Updates Automatically",
      "severity" : "medium"
    },
    {
      "id" : "os_software_update_deferral",
      "title" : "Ensure Software Update Deferment Is Less Than or Equal to $ODV Days",
      "severity" : "medium"
    },
    {
      "id" : "os_sudo_log_enforce",
      "title" : "Configure Sudo To Log Events",
      "severity" : "medium"
    },
    {
      "id" : "os_sudo_timeout_configure",
      "title" : "Configure Sudo Timeout Period to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sudoers_timestamp_type_configure",
      "title" : "Configure Sudoers Timestamp Type",
      "severity" : "medium"
    },
    {
      "id" : "os_system_wide_applications_configure",
      "title" : "Ensure Appropriate Permissions Are Enabled for System Wide Applications",
      "severity" : "medium"
    },
    {
      "id" : "os_terminal_secure_keyboard_enable",
      "title" : "Ensure Secure Keyboard Entry Terminal.app is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_time_server_enabled",
      "title" : "Enable Time Synchronization Daemon",
      "severity" : "medium"
    },
    {
      "id" : "os_unlock_active_user_session_disable",
      "title" : "Disable Login to Other User's Active and Locked Sessions",
      "severity" : "medium"
    },
    {
      "id" : "os_world_writable_system_folder_configure",
      "title" : "Ensure No World Writable Files Exist in the System Folder",
      "severity" : "medium"
    },
    {
      "id" : "os_writing_tools_disable",
      "title" : "Disable Apple Intelligence Writing Tools",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_account_lockout_enforce",
      "title" : "Limit Consecutive Failed Login Attempts to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_account_lockout_timeout_enforce",
      "title" : "Set Account Lockout Time to $ODV Minutes",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_history_enforce",
      "title" : "Prohibit Password Reuse for a Minimum of $ODV Generations",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_max_lifetime_enforce",
      "title" : "Restrict Maximum Password Lifetime to $ODV Days",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_minimum_length_enforce",
      "title" : "Require a Minimum Password Length of $ODV Characters",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_airplay_receiver_disable",
      "title" : "Disable Airplay Receiver",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_automatic_login_disable",
      "title" : "Disable Unattended or Automatic Logon to the System",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_bluetooth_sharing_disable",
      "title" : "Disable Bluetooth Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_critical_update_install_enforce",
      "title" : "Enforce Critical Security Updates to be Installed",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_diagnostics_reports_disable",
      "title" : "Disable Sending Diagnostic and Usage Data to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_external_intelligence_disable",
      "title" : "Disable External Intelligence Integrations",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_external_intelligence_sign_in_disable",
      "title" : "Disable External Intelligence Integration Sign In",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_filevault_enforce",
      "title" : "Enforce FileVault",
      "severity" : "high"
    },
    {
      "id" : "system_settings_firewall_enable",
      "title" : "Enable macOS Application Firewall",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_firewall_stealth_mode_enable",
      "title" : "Enable Firewall Stealth Mode",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_access_smb_disable",
      "title" : "Disable Guest Access to Shared SMB Folders",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_account_disable",
      "title" : "Disable the Guest Account",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_hot_corners_secure",
      "title" : "Secure Hot Corners",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_assistive_voice_disable",
      "title" : "Disable Sending Audio Recordings and Transcripts to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_search_disable",
      "title" : "Disable Improve Search Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_siri_dictation_disable",
      "title" : "Disable Improve Siri and Dictation Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_install_macos_updates_enforce",
      "title" : "Enforce macOS Updates are Automatically Installed",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_internet_sharing_disable",
      "title" : "Disable Internet Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_location_services_menu_enforce",
      "title" : "Ensure Location Services Is In the Menu Bar",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_loginwindow_loginwindowtext_enable",
      "title" : "Configure Login Window to Show A Custom Message",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_loginwindow_prompt_username_password_enforce",
      "title" : "Configure Login Window to Prompt for Username and Password",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_password_hints_disable",
      "title" : "Disable Password Hints",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_personalized_advertising_disable",
      "title" : "Disable Personalized Advertising",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_printer_sharing_disable",
      "title" : "Disable Printer Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_rae_disable",
      "title" : "Disable Remote Apple Events",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_remote_management_disable",
      "title" : "Disable Remote Management",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screen_sharing_disable",
      "title" : "Disable Screen Sharing and Apple Remote Desktop",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_ask_for_password_delay_enforce",
      "title" : "Enforce Session Lock After Screen Saver is Started",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_password_enforce",
      "title" : "Enforce Screen Saver Password",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_timeout_enforce",
      "title" : "Enforce Screen Saver Timeout",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_siri_disable",
      "title" : "Disable Siri",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_smbd_disable",
      "title" : "Disable Server Message Block Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_software_update_download_enforce",
      "title" : "Enforce Software Update Downloads Updates Automatically",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_softwareupdate_current",
      "title" : "Ensure Software Update is Updated and Current",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_ssh_disable",
      "title" : "Disable SSH Server for Remote Access Sessions",
      "severity" : "high"
    },
    {
      "id" : "system_settings_system_wide_preferences_configure",
      "title" : "Require Administrator Password to Modify System-Wide Preferences",
      "severity" : "high"
    },
    {
      "id" : "system_settings_time_machine_encrypted_configure",
      "title" : "Ensure Time Machine Volumes are Encrypted",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_time_server_configure",
      "title" : "Configure macOS to Use an Authorized Time Server",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_time_server_enforce",
      "title" : "Enforce macOS Time Synchronization",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_wake_network_access_disable",
      "title" : "Ensure Wake for Network Access Is Disabled",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_cis_manual",
      "title" : "CIS Manual Recommendations",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_filevault",
      "title" : "FileVault Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_password_policy",
      "title" : "Password Policy Supplemental",
      "severity" : "medium"
    }
  ]

  enabled_rules = {
    for rule in local.all_rules :
    rule.id => rule
    if !contains(var.disabled_rules, rule.id) && !contains(keys(var.exemptions), rule.id)
  }
}

# ---------------------------------------------------------------------------
# Device group — targets macOS 26 devices
# ---------------------------------------------------------------------------
resource "jamfplatform_device_group" "this" {
  name        = "${var.baseline_display_name} — macOS ${var.macos_version}"
  group_type  = "smart"
  device_type = "computer"
  criteria = [{
    criteria = "Operating System Version"
    operator = "greater than or equal"
    value    = var.macos_version_min
  }]
}

# ---------------------------------------------------------------------------
# Compliance Benchmark Engine — rule metadata from mSCP
# ---------------------------------------------------------------------------
data "jamfplatform_cbengine_rules" "this" {
  baseline_id = var.baseline_id
}

# ---------------------------------------------------------------------------
# Benchmark resource — all rules enabled by default, with per-rule overrides
# ---------------------------------------------------------------------------
resource "jamfplatform_cbengine_benchmark" "this" {
  title              = var.baseline_display_name
  description        = "${var.baseline_display_name} — mSCP ${var.mscp_branch} @ ${var.mscp_revision} — Managed by Terraform"
  source_baseline_id = var.baseline_id

  sources = [for s in data.jamfplatform_cbengine_rules.this.sources : {
    branch   = s.branch
    revision = s.revision
  }]

  rules = [
    for r in data.jamfplatform_cbengine_rules.this.rules : {
      id        = r.id
      enabled   = contains(keys(local.enabled_rules), r.id)
      odv_value = try(var.rule_overrides[r.id].odv_value, null)
    }
  ]

  target_device_group = jamfplatform_device_group.this.id
  enforcement_mode    = var.enforcement_mode
}
