# Compliance Baseline: NIST SP 800-53 Rev 5 — Privacy
# macOS 26 (26.0+)
# mSCP branch: tahoe  revision: pending_upstream
# NOTE: This baseline is not yet published in the upstream mSCP repository.
# This module will be regenerated by CI once the baseline YAML ships in
# https://github.com/usnistgov/macos_security
# Generated by scripts/generate_tf_compliance.py — DO NOT EDIT DIRECTLY

locals {
  all_rules = []

  enabled_rules = {
    for rule in local.all_rules :
    rule.id => rule
    if !contains(var.disabled_rules, rule.id) && !contains(keys(var.exemptions), rule.id)
  }
}

# ---------------------------------------------------------------------------
# Device group — targets macOS 26 devices
# ---------------------------------------------------------------------------
resource "jamfplatform_device_group" "this" {
  name        = "${var.baseline_display_name} — macOS ${var.macos_version}"
  group_type  = "smart"
  device_type = "computer"
  criteria = [{
    criteria = "Operating System Version"
    operator = "greater than or equal"
    value    = var.macos_version_min
  }]
}

# ---------------------------------------------------------------------------
# Benchmark resource — pending upstream baseline definition
# ---------------------------------------------------------------------------
resource "jamfplatform_cbengine_benchmark" "this" {
  title       = var.baseline_display_name
  description = "${var.baseline_display_name} — mSCP ${var.mscp_branch} @ ${var.mscp_revision} — Managed by Terraform"
  source_baseline_id = var.baseline_id

  sources = []

  rules = []

  target_device_group = jamfplatform_device_group.this.id
  enforcement_mode    = var.enforcement_mode
}
