# Compliance Baseline: CMMC 2.0 — Level 1
# macOS 26 (26.0+)
# mSCP branch: tahoe  revision: rev3.0
# Generated by scripts/generate_tf_compliance.py — DO NOT EDIT DIRECTLY

locals {
  # All rules for this baseline (id, title, severity)
  all_rules = [
    {
      "id" : "auth_smartcard_allow",
      "title" : "Allow Smartcard Authentication",
      "severity" : "medium"
    },
    {
      "id" : "auth_smartcard_enforce",
      "title" : "Enforce Smartcard Authentication",
      "severity" : "medium"
    },
    {
      "id" : "auth_ssh_password_authentication_disable",
      "title" : "Disable Password Authentication for SSH",
      "severity" : "high"
    },
    {
      "id" : "icloud_addressbook_disable",
      "title" : "Disable iCloud Address Book",
      "severity" : "medium"
    },
    {
      "id" : "icloud_appleid_system_settings_disable",
      "title" : "Disable the System Setting for Apple ID",
      "severity" : "high"
    },
    {
      "id" : "icloud_bookmarks_disable",
      "title" : "Disable iCloud Bookmarks",
      "severity" : "medium"
    },
    {
      "id" : "icloud_calendar_disable",
      "title" : "Disable the iCloud Calendar Services",
      "severity" : "medium"
    },
    {
      "id" : "icloud_drive_disable",
      "title" : "Disable iCloud Document Sync",
      "severity" : "medium"
    },
    {
      "id" : "icloud_freeform_disable",
      "title" : "Disable the iCloud Freeform Services",
      "severity" : "medium"
    },
    {
      "id" : "icloud_game_center_disable",
      "title" : "Disable iCloud Game Center",
      "severity" : "medium"
    },
    {
      "id" : "icloud_keychain_disable",
      "title" : "Disable iCloud Keychain Sync",
      "severity" : "medium"
    },
    {
      "id" : "icloud_mail_disable",
      "title" : "Disable iCloud Mail",
      "severity" : "medium"
    },
    {
      "id" : "icloud_notes_disable",
      "title" : "Disable iCloud Notes",
      "severity" : "medium"
    },
    {
      "id" : "icloud_photos_disable",
      "title" : "Disable iCloud Photo Library",
      "severity" : "medium"
    },
    {
      "id" : "icloud_private_relay_disable",
      "title" : "Disable iCloud Private Relay",
      "severity" : "medium"
    },
    {
      "id" : "icloud_reminders_disable",
      "title" : "Disable iCloud Reminders",
      "severity" : "medium"
    },
    {
      "id" : "icloud_sync_disable",
      "title" : "Disable iCloud Desktop and Document Folder Sync",
      "severity" : "medium"
    },
    {
      "id" : "os_account_modification_disable",
      "title" : "Disable AppleID and Internet Account Modifications",
      "severity" : "medium"
    },
    {
      "id" : "os_airdrop_disable",
      "title" : "Disable AirDrop",
      "severity" : "medium"
    },
    {
      "id" : "os_appleid_prompt_disable",
      "title" : "Disable Apple ID Setup during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_authenticated_root_enable",
      "title" : "Enable Authenticated Root",
      "severity" : "medium"
    },
    {
      "id" : "os_config_data_install_enforce",
      "title" : "Enforce Installation of XProtect Remediator and Gatekeeper Updates Automatically",
      "severity" : "medium"
    },
    {
      "id" : "os_dictation_disable",
      "title" : "Disable Dictation",
      "severity" : "medium"
    },
    {
      "id" : "os_filevault_autologin_disable",
      "title" : "Disable FileVault Automatic Login",
      "severity" : "medium"
    },
    {
      "id" : "os_firmware_password_require",
      "title" : "Enable Firmware Password",
      "severity" : "medium"
    },
    {
      "id" : "os_gatekeeper_enable",
      "title" : "Enable Gatekeeper",
      "severity" : "high"
    },
    {
      "id" : "os_genmoji_disable",
      "title" : "Disable Genmoji AI Creation",
      "severity" : "medium"
    },
    {
      "id" : "os_handoff_disable",
      "title" : "Disable Handoff",
      "severity" : "medium"
    },
    {
      "id" : "os_home_folders_secure",
      "title" : "Secure User's Home Folders",
      "severity" : "medium"
    },
    {
      "id" : "os_httpd_disable",
      "title" : "Disable the Built-in Web Server",
      "severity" : "medium"
    },
    {
      "id" : "os_icloud_storage_prompt_disable",
      "title" : "Disable iCloud Storage Setup during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_image_playground_disable",
      "title" : "Disable Apple Intelligence Image Playground",
      "severity" : "medium"
    },
    {
      "id" : "os_iphone_mirroring_disable",
      "title" : "Disable iPhone Mirroring",
      "severity" : "medium"
    },
    {
      "id" : "os_mail_smart_reply_disable",
      "title" : "Disable Apple Intelligence Mail Smart Replies",
      "severity" : "medium"
    },
    {
      "id" : "os_mail_summary_disable",
      "title" : "Disable Apple Intelligence Mail Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_nfsd_disable",
      "title" : "Disable Network File System Service",
      "severity" : "medium"
    },
    {
      "id" : "os_notes_transcription_disable",
      "title" : "Disable Apple Intelligence Notes Transcription",
      "severity" : "medium"
    },
    {
      "id" : "os_notes_transcription_summary_disable",
      "title" : "Disable Apple Intelligence Notes Transcription Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_on_device_dictation_enforce",
      "title" : "Enforce On Device Dictation",
      "severity" : "medium"
    },
    {
      "id" : "os_photos_enhanced_search_disable",
      "title" : "Disable Photos Enhanced Visual Search",
      "severity" : "medium"
    },
    {
      "id" : "os_recovery_lock_enable",
      "title" : "Enable Recovery Lock",
      "severity" : "medium"
    },
    {
      "id" : "os_root_disable",
      "title" : "Disable Root Login",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_reader_summary_disable",
      "title" : "Disable Apple Intelligence Safari Reader Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_sip_enable",
      "title" : "Ensure System Integrity Protection is Enabled",
      "severity" : "high"
    },
    {
      "id" : "os_siri_prompt_disable",
      "title" : "Disable Siri Setup during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_skip_apple_intelligence_enable",
      "title" : "Disable Apple Intelligence During Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_skip_unlock_with_watch_enable",
      "title" : "Disable Unlock with Apple Watch During Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_tftpd_disable",
      "title" : "Disable Trivial File Transfer Protocol Service",
      "severity" : "high"
    },
    {
      "id" : "os_unlock_active_user_session_disable",
      "title" : "Disable Login to Other User's Active and Locked Sessions",
      "severity" : "medium"
    },
    {
      "id" : "os_uucp_disable",
      "title" : "Disable Unix-to-Unix Copy Protocol Service",
      "severity" : "medium"
    },
    {
      "id" : "os_writing_tools_disable",
      "title" : "Disable Apple Intelligence Writing Tools",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_automatic_login_disable",
      "title" : "Disable Unattended or Automatic Logon to the System",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_bluetooth_sharing_disable",
      "title" : "Disable Bluetooth Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_critical_update_install_enforce",
      "title" : "Enforce Critical Security Updates to be Installed",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_diagnostics_reports_disable",
      "title" : "Disable Sending Diagnostic and Usage Data to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_external_intelligence_disable",
      "title" : "Disable External Intelligence Integrations",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_external_intelligence_sign_in_disable",
      "title" : "Disable External Intelligence Integration Sign In",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_find_my_disable",
      "title" : "Disable Find My Service",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_firewall_enable",
      "title" : "Enable macOS Application Firewall",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_firewall_stealth_mode_enable",
      "title" : "Enable Firewall Stealth Mode",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_access_smb_disable",
      "title" : "Disable Guest Access to Shared SMB Folders",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_account_disable",
      "title" : "Disable the Guest Account",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_assistive_voice_disable",
      "title" : "Disable Sending Audio Recordings and Transcripts to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_search_disable",
      "title" : "Disable Improve Search Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_siri_dictation_disable",
      "title" : "Disable Improve Siri and Dictation Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_internet_accounts_disable",
      "title" : "Disable the Internet Accounts System Preference Pane",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_internet_sharing_disable",
      "title" : "Disable Internet Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_loginwindow_prompt_username_password_enforce",
      "title" : "Configure Login Window to Prompt for Username and Password",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_media_sharing_disabled",
      "title" : "Disable Media Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_personalized_advertising_disable",
      "title" : "Disable Personalized Advertising",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_rae_disable",
      "title" : "Disable Remote Apple Events",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screen_sharing_disable",
      "title" : "Disable Screen Sharing and Apple Remote Desktop",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_security_update_install",
      "title" : "Enforce Automatic Installs of Available Security Updates using DDM.",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_siri_disable",
      "title" : "Disable Siri",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_smbd_disable",
      "title" : "Disable Server Message Block Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_softwareupdate_current",
      "title" : "Ensure Software Update is Updated and Current",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_ssh_disable",
      "title" : "Disable SSH Server for Remote Access Sessions",
      "severity" : "high"
    },
    {
      "id" : "system_settings_ssh_enable",
      "title" : "Enable SSH Server for Remote Access Sessions",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_system_wide_preferences_configure",
      "title" : "Require Administrator Password to Modify System-Wide Preferences",
      "severity" : "high"
    },
    {
      "id" : "os_logical_access",
      "title" : "Enforce Approved Authorization for Logical Access",
      "severity" : "medium"
    },
    {
      "id" : "os_malicious_code_prevention",
      "title" : "Ensure the System Implements Malicious Code Protection Mechanisms",
      "severity" : "medium"
    },
    {
      "id" : "os_auth_peripherals",
      "title" : "Must Authenticate Before Establishing a Connection",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_controls",
      "title" : "Out of Scope Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_filevault",
      "title" : "FileVault Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_firewall_pf",
      "title" : "Packet Filter (pf) Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_password_policy",
      "title" : "Password Policy Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_smartcard",
      "title" : "Smartcard Supplemental",
      "severity" : "medium"
    }
  ]

  enabled_rules = {
    for rule in local.all_rules :
    rule.id => rule
    if !contains(var.disabled_rules, rule.id) && !contains(keys(var.exemptions), rule.id)
  }
}

# ---------------------------------------------------------------------------
# Device group — targets macOS 26 devices
# ---------------------------------------------------------------------------
resource "jamfplatform_device_group" "this" {
  name        = "${var.baseline_display_name} — macOS ${var.macos_version}"
  group_type  = "smart"
  device_type = "computer"
  criteria = [{
    criteria = "Operating System Version"
    operator = "greater than or equal"
    value    = var.macos_version_min
  }]
}

# ---------------------------------------------------------------------------
# Compliance Benchmark Engine — rule metadata from mSCP
# ---------------------------------------------------------------------------
data "jamfplatform_cbengine_rules" "this" {
  baseline_id = var.baseline_id
}

# ---------------------------------------------------------------------------
# Benchmark resource — all rules enabled by default, with per-rule overrides
# ---------------------------------------------------------------------------
resource "jamfplatform_cbengine_benchmark" "this" {
  title              = var.baseline_display_name
  description        = "${var.baseline_display_name} — mSCP ${var.mscp_branch} @ ${var.mscp_revision} — Managed by Terraform"
  source_baseline_id = var.baseline_id

  sources = [for s in data.jamfplatform_cbengine_rules.this.sources : {
    branch   = s.branch
    revision = s.revision
  }]

  rules = [
    for r in data.jamfplatform_cbengine_rules.this.rules : {
      id        = r.id
      enabled   = contains(keys(local.enabled_rules), r.id)
      odv_value = try(var.rule_overrides[r.id].odv_value, null)
    }
  ]

  target_device_group = jamfplatform_device_group.this.id
  enforcement_mode    = var.enforcement_mode
}
