# Outputs for NIST SP 800-53 Rev 5 — High
# Generated by scripts/generate_tf_compliance.py — DO NOT EDIT DIRECTLY

output "benchmark_id" {
  value       = jamfplatform_cbengine_benchmark.this.id
  description = "ID of the created benchmark resource"
}

output "device_group_id" {
  value       = jamfplatform_device_group.this.id
  description = "ID of the created device group"
}

output "exemptions" {
  value = {
    for k, v in var.exemptions : k => merge(v, {
      module        = var.baseline_id
      macos_version = var.macos_version
      timestamp     = timestamp()
    })
  }
  description = "Active exemptions with audit justification"
}

# Deprecated alias for backwards compatibility
output "exemption_report" {
  value = {
    for k, v in var.exemptions : k => merge(v, {
      module        = var.baseline_id
      macos_version = var.macos_version
      timestamp     = timestamp()
    })
  }
  description = "Active exemptions with audit justification (deprecated, use exemptions)"
}
