# Compliance Baseline: CNSSI 1253 — Low
# macOS 26 (26.0+)
# mSCP branch: tahoe  revision: rev3.0
# Generated by scripts/generate_tf_compliance.py — DO NOT EDIT DIRECTLY

locals {
  # All rules for this baseline (id, title, severity)
  all_rules = [
    {
      "id" : "audit_acls_files_configure",
      "title" : "Configure Audit Log Files to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_acls_folders_configure",
      "title" : "Configure Audit Log Folder to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_auditd_enabled",
      "title" : "Enable Security Auditing",
      "severity" : "medium"
    },
    {
      "id" : "audit_configure_capacity_notify",
      "title" : "Configure Audit Capacity Warning",
      "severity" : "low"
    },
    {
      "id" : "audit_control_acls_configure",
      "title" : "Configure Audit_Control to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_group_configure",
      "title" : "Configure Audit_Control Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_mode_configure",
      "title" : "Configure Audit_Control Owner to Mode 440 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_owner_configure",
      "title" : "Configure Audit_Control Owner to Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_failure_halt",
      "title" : "Configure System to Shut Down Upon Audit Failure",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_group_configure",
      "title" : "Configure Audit Log Files Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_mode_configure",
      "title" : "Configure Audit Log Files to Mode 440 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_owner_configure",
      "title" : "Configure Audit Log Files to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_aa_configure",
      "title" : "Configure System to Audit All Authorization and Authentication Events",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_ad_configure",
      "title" : "Configure System to Audit All Administrative Action Events",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_ex_configure",
      "title" : "Configure System to Audit All Failed Program Execution on the System",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_fd_configure",
      "title" : "Configure System to Audit All Deletions of Object Attributes",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_fm_configure",
      "title" : "Configure System to Audit All Changes of Object Attributes",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_fm_failed_configure",
      "title" : "Configure System to Audit All Failed Change of Object Attributes",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_fr_configure",
      "title" : "Configure System to Audit All Failed Read Actions on the System",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_fw_configure",
      "title" : "Configure System to Audit All Failed Write Actions on the System",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_lo_configure",
      "title" : "Configure System to Audit All Log In and Log Out Events",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_group_configure",
      "title" : "Configure Audit Log Folders Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_owner_configure",
      "title" : "Configure Audit Log Folders to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_folders_mode_configure",
      "title" : "Configure Audit Log Folders to Mode 700 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_retention_configure",
      "title" : "Configure Audit Retention to $ODV",
      "severity" : "low"
    },
    {
      "id" : "audit_settings_failure_notify",
      "title" : "Configure Audit Failure Notification",
      "severity" : "medium"
    },
    {
      "id" : "auth_pam_login_smartcard_enforce",
      "title" : "Enforce Multifactor Authentication for Login",
      "severity" : "medium"
    },
    {
      "id" : "auth_pam_su_smartcard_enforce",
      "title" : "Enforce Multifactor Authentication for the su Command",
      "severity" : "medium"
    },
    {
      "id" : "auth_pam_sudo_smartcard_enforce",
      "title" : "Enforce Multifactor Authentication for Privilege Escalation Through the sudo Command",
      "severity" : "medium"
    },
    {
      "id" : "auth_smartcard_allow",
      "title" : "Allow Smartcard Authentication",
      "severity" : "medium"
    },
    {
      "id" : "auth_smartcard_certificate_trust_enforce_high",
      "title" : "Set Smartcard Certificate Trust to High",
      "severity" : "medium"
    },
    {
      "id" : "auth_smartcard_certificate_trust_enforce_moderate",
      "title" : "Set Smartcard Certificate Trust to Moderate",
      "severity" : "medium"
    },
    {
      "id" : "auth_smartcard_enforce",
      "title" : "Enforce Smartcard Authentication",
      "severity" : "medium"
    },
    {
      "id" : "auth_ssh_password_authentication_disable",
      "title" : "Disable Password Authentication for SSH",
      "severity" : "high"
    },
    {
      "id" : "icloud_addressbook_disable",
      "title" : "Disable iCloud Address Book",
      "severity" : "medium"
    },
    {
      "id" : "icloud_appleid_system_settings_disable",
      "title" : "Disable the System Setting for Apple ID",
      "severity" : "high"
    },
    {
      "id" : "icloud_bookmarks_disable",
      "title" : "Disable iCloud Bookmarks",
      "severity" : "medium"
    },
    {
      "id" : "icloud_calendar_disable",
      "title" : "Disable the iCloud Calendar Services",
      "severity" : "medium"
    },
    {
      "id" : "icloud_drive_disable",
      "title" : "Disable iCloud Document Sync",
      "severity" : "medium"
    },
    {
      "id" : "icloud_freeform_disable",
      "title" : "Disable the iCloud Freeform Services",
      "severity" : "medium"
    },
    {
      "id" : "icloud_game_center_disable",
      "title" : "Disable iCloud Game Center",
      "severity" : "medium"
    },
    {
      "id" : "icloud_keychain_disable",
      "title" : "Disable iCloud Keychain Sync",
      "severity" : "medium"
    },
    {
      "id" : "icloud_mail_disable",
      "title" : "Disable iCloud Mail",
      "severity" : "medium"
    },
    {
      "id" : "icloud_notes_disable",
      "title" : "Disable iCloud Notes",
      "severity" : "medium"
    },
    {
      "id" : "icloud_photos_disable",
      "title" : "Disable iCloud Photo Library",
      "severity" : "medium"
    },
    {
      "id" : "icloud_private_relay_disable",
      "title" : "Disable iCloud Private Relay",
      "severity" : "medium"
    },
    {
      "id" : "icloud_reminders_disable",
      "title" : "Disable iCloud Reminders",
      "severity" : "medium"
    },
    {
      "id" : "icloud_sync_disable",
      "title" : "Disable iCloud Desktop and Document Folder Sync",
      "severity" : "medium"
    },
    {
      "id" : "os_account_modification_disable",
      "title" : "Disable AppleID and Internet Account Modifications",
      "severity" : "medium"
    },
    {
      "id" : "os_airdrop_disable",
      "title" : "Disable AirDrop",
      "severity" : "medium"
    },
    {
      "id" : "os_appleid_prompt_disable",
      "title" : "Disable Apple ID Setup during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_asl_log_files_owner_group_configure",
      "title" : "Configure Apple System Log Files Owned by Root and Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "os_asl_log_files_permissions_configure",
      "title" : "Configure Apple System Log Files To Mode 640 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "os_authenticated_root_enable",
      "title" : "Enable Authenticated Root",
      "severity" : "medium"
    },
    {
      "id" : "os_blank_bluray_disable",
      "title" : "Disable Blank Blu Ray",
      "severity" : "medium"
    },
    {
      "id" : "os_blank_cd_disable",
      "title" : "Disable Blank CD",
      "severity" : "medium"
    },
    {
      "id" : "os_blank_dvd_disable",
      "title" : "Disable Blank DVD",
      "severity" : "medium"
    },
    {
      "id" : "os_bluray_read_only_enforce",
      "title" : "Enforce Blu Ray Read Only",
      "severity" : "medium"
    },
    {
      "id" : "os_bonjour_disable",
      "title" : "Disable Bonjour Multicast",
      "severity" : "medium"
    },
    {
      "id" : "os_burn_support_disable",
      "title" : "Disable Burn Support",
      "severity" : "low"
    },
    {
      "id" : "os_calendar_app_disable",
      "title" : "Disable Calendar.app",
      "severity" : "medium"
    },
    {
      "id" : "os_cd_read_only_enforce",
      "title" : "Enforce CD Read Only",
      "severity" : "medium"
    },
    {
      "id" : "os_certificate_authority_trust",
      "title" : "Issue or Obtain Public Key Certificates from an Approved Service Provider",
      "severity" : "high"
    },
    {
      "id" : "os_config_data_install_enforce",
      "title" : "Enforce Installation of XProtect Remediator and Gatekeeper Updates Automatically",
      "severity" : "medium"
    },
    {
      "id" : "os_config_profile_ui_install_disable",
      "title" : "Disable Installation of Configuration Profiles through the User Interface",
      "severity" : "medium"
    },
    {
      "id" : "os_dictation_disable",
      "title" : "Disable Dictation",
      "severity" : "medium"
    },
    {
      "id" : "os_disk_image_disable",
      "title" : "Disable Disk Images",
      "severity" : "medium"
    },
    {
      "id" : "os_dvdram_disable",
      "title" : "Disable DVD-RAM",
      "severity" : "medium"
    },
    {
      "id" : "os_erase_content_and_settings_disable",
      "title" : "Disable Erase Content and Settings",
      "severity" : "medium"
    },
    {
      "id" : "os_external_storage_access_defined",
      "title" : "Access to External Storage Must Be Defined",
      "severity" : "medium"
    },
    {
      "id" : "os_facetime_app_disable",
      "title" : "Disable FaceTime.app",
      "severity" : "medium"
    },
    {
      "id" : "os_filevault_autologin_disable",
      "title" : "Disable FileVault Automatic Login",
      "severity" : "medium"
    },
    {
      "id" : "os_firewall_default_deny_require",
      "title" : "Control Connections to Other Systems via a Deny-All and Allow-by-Exception Firewall Policy",
      "severity" : "medium"
    },
    {
      "id" : "os_firmware_password_require",
      "title" : "Enable Firmware Password",
      "severity" : "medium"
    },
    {
      "id" : "os_gatekeeper_enable",
      "title" : "Enable Gatekeeper",
      "severity" : "high"
    },
    {
      "id" : "os_genmoji_disable",
      "title" : "Disable Genmoji AI Creation",
      "severity" : "medium"
    },
    {
      "id" : "os_handoff_disable",
      "title" : "Disable Handoff",
      "severity" : "medium"
    },
    {
      "id" : "os_home_folders_default",
      "title" : "Configure User's Home Folders to Apple's Default",
      "severity" : "medium"
    },
    {
      "id" : "os_home_folders_secure",
      "title" : "Secure User's Home Folders",
      "severity" : "medium"
    },
    {
      "id" : "os_httpd_disable",
      "title" : "Disable the Built-in Web Server",
      "severity" : "medium"
    },
    {
      "id" : "os_icloud_storage_prompt_disable",
      "title" : "Disable iCloud Storage Setup during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_image_playground_disable",
      "title" : "Disable Apple Intelligence Image Playground",
      "severity" : "medium"
    },
    {
      "id" : "os_install_log_retention_configure",
      "title" : "Configure Install.log Retention to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_iphone_mirroring_disable",
      "title" : "Disable iPhone Mirroring",
      "severity" : "medium"
    },
    {
      "id" : "os_ir_support_disable",
      "title" : "Disable Infrared (IR) support",
      "severity" : "medium"
    },
    {
      "id" : "os_loginwindow_adminhostinfo_disabled",
      "title" : "Prevent AdminHostInfo from Being Available at Login Window",
      "severity" : "medium"
    },
    {
      "id" : "os_mail_app_disable",
      "title" : "Disable Mail App",
      "severity" : "medium"
    },
    {
      "id" : "os_mail_smart_reply_disable",
      "title" : "Disable Apple Intelligence Mail Smart Replies",
      "severity" : "medium"
    },
    {
      "id" : "os_mail_summary_disable",
      "title" : "Disable Apple Intelligence Mail Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_mdm_require",
      "title" : "Enforce Enrollment in Mobile Device Management",
      "severity" : "medium"
    },
    {
      "id" : "os_messages_app_disable",
      "title" : "Disable Messages App",
      "severity" : "low"
    },
    {
      "id" : "os_newsyslog_files_owner_group_configure",
      "title" : "Configure System Log Files Owned by Root and Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "os_newsyslog_files_permissions_configure",
      "title" : "Configure System Log Files to Mode 640 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "os_nfsd_disable",
      "title" : "Disable Network File System Service",
      "severity" : "medium"
    },
    {
      "id" : "os_notes_transcription_disable",
      "title" : "Disable Apple Intelligence Notes Transcription",
      "severity" : "medium"
    },
    {
      "id" : "os_notes_transcription_summary_disable",
      "title" : "Disable Apple Intelligence Notes Transcription Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_on_device_dictation_enforce",
      "title" : "Enforce On Device Dictation",
      "severity" : "medium"
    },
    {
      "id" : "os_parental_controls_enable",
      "title" : "Enable Parental Controls",
      "severity" : "medium"
    },
    {
      "id" : "os_password_autofill_disable",
      "title" : "Disable Password Autofill",
      "severity" : "medium"
    },
    {
      "id" : "os_password_hint_remove",
      "title" : "Remove Password Hint From User Accounts",
      "severity" : "medium"
    },
    {
      "id" : "os_password_proximity_disable",
      "title" : "Disable Proximity Based Password Sharing Requests",
      "severity" : "medium"
    },
    {
      "id" : "os_password_sharing_disable",
      "title" : "Disable Password Sharing",
      "severity" : "medium"
    },
    {
      "id" : "os_photos_enhanced_search_disable",
      "title" : "Disable Photos Enhanced Visual Search",
      "severity" : "medium"
    },
    {
      "id" : "os_policy_banner_loginwindow_enforce",
      "title" : "Display Policy Banner at Login Window",
      "severity" : "medium"
    },
    {
      "id" : "os_policy_banner_ssh_configure",
      "title" : "Display Policy Banner at Remote Login",
      "severity" : "medium"
    },
    {
      "id" : "os_policy_banner_ssh_enforce",
      "title" : "Enforce SSH to Display Policy Banner",
      "severity" : "medium"
    },
    {
      "id" : "os_power_nap_disable",
      "title" : "Disable Power Nap",
      "severity" : "medium"
    },
    {
      "id" : "os_privacy_setup_prompt_disable",
      "title" : "Disable Privacy Setup Services During Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_recovery_lock_enable",
      "title" : "Enable Recovery Lock",
      "severity" : "medium"
    },
    {
      "id" : "os_removable_media_disable",
      "title" : "Disable Removable Storage Devices",
      "severity" : "medium"
    },
    {
      "id" : "os_root_disable",
      "title" : "Disable Root Login",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_reader_summary_disable",
      "title" : "Disable Apple Intelligence Safari Reader Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_screensaver_loginwindow_enforce",
      "title" : "Enforce Screen Saver at Login Window",
      "severity" : "medium"
    },
    {
      "id" : "os_setup_assistant_filevault_enforce",
      "title" : "Enforce FileVault in Setup Assistant",
      "severity" : "high"
    },
    {
      "id" : "os_sip_enable",
      "title" : "Ensure System Integrity Protection is Enabled",
      "severity" : "high"
    },
    {
      "id" : "os_siri_prompt_disable",
      "title" : "Disable Siri Setup during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_skip_apple_intelligence_enable",
      "title" : "Disable Apple Intelligence During Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_skip_screen_time_prompt_enable",
      "title" : "Disable Screen Time Prompt During Setup Assistant",
      "severity" : "low"
    },
    {
      "id" : "os_skip_unlock_with_watch_enable",
      "title" : "Disable Unlock with Apple Watch During Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_ssh_fips_compliant",
      "title" : "Limit SSH to FIPS Compliant Connections",
      "severity" : "high"
    },
    {
      "id" : "os_ssh_server_alive_count_max_configure",
      "title" : "Set SSH Active Server Alive Maximum to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_ssh_server_alive_interval_configure",
      "title" : "Configure SSH ServerAliveInterval option set to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_channel_timeout_configure",
      "title" : "Configure SSHD Channel Timeout to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_client_alive_count_max_configure",
      "title" : "Configure SSHD ClientAliveCountMax to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_client_alive_interval_configure",
      "title" : "Configure SSHD ClientAliveInterval to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_fips_compliant",
      "title" : "Limit SSHD to FIPS Compliant Connections",
      "severity" : "high"
    },
    {
      "id" : "os_sshd_login_grace_time_configure",
      "title" : "Set Login Grace Time to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_per_source_penalties_configure",
      "title" : "Configure SSHD PerSourcePenalties",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_permit_root_login_configure",
      "title" : "Disable Root Login for SSH",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_unused_connection_timeout_configure",
      "title" : "Configure SSHD Unused Connection Timeout to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sudo_log_enforce",
      "title" : "Configure Sudo To Log Events",
      "severity" : "medium"
    },
    {
      "id" : "os_sudoers_timestamp_type_configure",
      "title" : "Configure Sudoers Timestamp Type",
      "severity" : "medium"
    },
    {
      "id" : "os_system_read_only",
      "title" : "Ensure System Volume is Read Only",
      "severity" : "medium"
    },
    {
      "id" : "os_tftpd_disable",
      "title" : "Disable Trivial File Transfer Protocol Service",
      "severity" : "high"
    },
    {
      "id" : "os_time_server_enabled",
      "title" : "Enable Time Synchronization Daemon",
      "severity" : "medium"
    },
    {
      "id" : "os_touchid_prompt_disable",
      "title" : "Disable TouchID Prompt during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_unlock_active_user_session_disable",
      "title" : "Disable Login to Other User's Active and Locked Sessions",
      "severity" : "medium"
    },
    {
      "id" : "os_user_app_installation_prohibit",
      "title" : "Prohibit User Installation of Software into /Users/",
      "severity" : "medium"
    },
    {
      "id" : "os_uucp_disable",
      "title" : "Disable Unix-to-Unix Copy Protocol Service",
      "severity" : "medium"
    },
    {
      "id" : "os_writing_tools_disable",
      "title" : "Disable Apple Intelligence Writing Tools",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_account_lockout_enforce",
      "title" : "Limit Consecutive Failed Login Attempts to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_account_lockout_timeout_enforce",
      "title" : "Set Account Lockout Time to $ODV Minutes",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_alpha_numeric_enforce",
      "title" : "Require Passwords Contain a Minimum of One Numeric Character",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_custom_regex_enforce",
      "title" : "Require Passwords to Match the Defined Custom Regular Expression",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_history_enforce",
      "title" : "Prohibit Password Reuse for a Minimum of $ODV Generations",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_lower_case_character_enforce",
      "title" : "Require Passwords Contain a Minimum of One Lowercase Character",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_max_lifetime_enforce",
      "title" : "Restrict Maximum Password Lifetime to $ODV Days",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_minimum_length_enforce",
      "title" : "Require a Minimum Password Length of $ODV Characters",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_minimum_lifetime_enforce",
      "title" : "Set Minimum Password Lifetime to $ODV Hours",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_simple_sequence_disable",
      "title" : "Prohibit Repeating, Ascending, and Descending Character Sequences",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_special_character_enforce",
      "title" : "Require Passwords Contain a Minimum of One Special Character",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_upper_case_character_enforce",
      "title" : "Require Passwords Contain a Minimum of One Uppercase Character",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_airplay_receiver_disable",
      "title" : "Disable Airplay Receiver",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_apple_watch_unlock_disable",
      "title" : "Prevent Apple Watch from Terminating a Session Lock",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_automatic_login_disable",
      "title" : "Disable Unattended or Automatic Logon to the System",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_automatic_logout_enforce",
      "title" : "Enforce Auto Logout After $ODV Seconds of Inactivity",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_bluetooth_disable",
      "title" : "Disable Bluetooth When no Approved Device is Connected",
      "severity" : "high"
    },
    {
      "id" : "system_settings_bluetooth_settings_disable",
      "title" : "Disable the Bluetooth System Settings Pane",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_bluetooth_sharing_disable",
      "title" : "Disable Bluetooth Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_content_caching_disable",
      "title" : "Disable Content Caching Service",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_critical_update_install_enforce",
      "title" : "Enforce Critical Security Updates to be Installed",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_diagnostics_reports_disable",
      "title" : "Disable Sending Diagnostic and Usage Data to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_external_intelligence_disable",
      "title" : "Disable External Intelligence Integrations",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_external_intelligence_sign_in_disable",
      "title" : "Disable External Intelligence Integration Sign In",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_filevault_enforce",
      "title" : "Enforce FileVault",
      "severity" : "high"
    },
    {
      "id" : "system_settings_find_my_disable",
      "title" : "Disable Find My Service",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_firewall_enable",
      "title" : "Enable macOS Application Firewall",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_firewall_stealth_mode_enable",
      "title" : "Enable Firewall Stealth Mode",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_gatekeeper_identified_developers_allowed",
      "title" : "Apply Gatekeeper Settings to Block Applications from Unidentified Developers",
      "severity" : "high"
    },
    {
      "id" : "system_settings_gatekeeper_override_disallow",
      "title" : "Configure Gatekeeper to Disallow End User Override",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_access_smb_disable",
      "title" : "Disable Guest Access to Shared SMB Folders",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_account_disable",
      "title" : "Disable the Guest Account",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_hot_corners_disable",
      "title" : "Disable Hot Corners",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_hot_corners_secure",
      "title" : "Secure Hot Corners",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_assistive_voice_disable",
      "title" : "Disable Sending Audio Recordings and Transcripts to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_search_disable",
      "title" : "Disable Improve Search Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_siri_dictation_disable",
      "title" : "Disable Improve Siri and Dictation Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_internet_accounts_disable",
      "title" : "Disable the Internet Accounts System Preference Pane",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_internet_sharing_disable",
      "title" : "Disable Internet Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_location_services_disable",
      "title" : "Disable Location Services",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_loginwindow_prompt_username_password_enforce",
      "title" : "Configure Login Window to Prompt for Username and Password",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_media_sharing_disabled",
      "title" : "Disable Media Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_password_hints_disable",
      "title" : "Disable Password Hints",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_personalized_advertising_disable",
      "title" : "Disable Personalized Advertising",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_printer_sharing_disable",
      "title" : "Disable Printer Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_rae_disable",
      "title" : "Disable Remote Apple Events",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_remote_management_disable",
      "title" : "Disable Remote Management",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screen_sharing_disable",
      "title" : "Disable Screen Sharing and Apple Remote Desktop",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_ask_for_password_delay_enforce",
      "title" : "Enforce Session Lock After Screen Saver is Started",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_password_enforce",
      "title" : "Enforce Screen Saver Password",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_timeout_enforce",
      "title" : "Enforce Screen Saver Timeout",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_security_update_install",
      "title" : "Enforce Automatic Installs of Available Security Updates using DDM.",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_siri_disable",
      "title" : "Disable Siri",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_siri_settings_disable",
      "title" : "Disable the System Settings Pane for Siri",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_smbd_disable",
      "title" : "Disable Server Message Block Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_ssh_disable",
      "title" : "Disable SSH Server for Remote Access Sessions",
      "severity" : "high"
    },
    {
      "id" : "system_settings_ssh_enable",
      "title" : "Enable SSH Server for Remote Access Sessions",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_system_wide_preferences_configure",
      "title" : "Require Administrator Password to Modify System-Wide Preferences",
      "severity" : "high"
    },
    {
      "id" : "system_settings_time_server_configure",
      "title" : "Configure macOS to Use an Authorized Time Server",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_time_server_enforce",
      "title" : "Enforce macOS Time Synchronization",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_token_removal_enforce",
      "title" : "Configure User Session Lock When a Smart Token is Removed",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_touch_id_settings_disable",
      "title" : "Disable the Touch ID System Settings Pane",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_touchid_unlock_disable",
      "title" : "Disable TouchID for Unlocking the Device",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_usb_restricted_mode",
      "title" : "USB Devices Must be Authorized Before Allowing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_wallet_applepay_settings_disable",
      "title" : "Disable the System Settings Pane for Wallet and Apple Pay",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_wifi_disable",
      "title" : "Disable Wi-Fi Interface",
      "severity" : "medium"
    },
    {
      "id" : "os_allow_info_passed",
      "title" : "Allow Information Transfer with Other Operating Systems",
      "severity" : "medium"
    },
    {
      "id" : "os_application_sandboxing",
      "title" : "Ensure Separate Execution Domain for Processes",
      "severity" : "medium"
    },
    {
      "id" : "os_change_security_attributes",
      "title" : "Allow Administrators to Modify Security Settings and System Attributes",
      "severity" : "medium"
    },
    {
      "id" : "os_grant_privs",
      "title" : "Allow Administrators to Promote Other Users to Administrator Status",
      "severity" : "medium"
    },
    {
      "id" : "os_implement_cryptography",
      "title" : "Configure the System to Implement Approved Cryptography to Protect Information",
      "severity" : "medium"
    },
    {
      "id" : "os_logical_access",
      "title" : "Enforce Approved Authorization for Logical Access",
      "severity" : "medium"
    },
    {
      "id" : "os_logoff_capability_and_message",
      "title" : "Display logoff capability and message to prevent exploitation",
      "severity" : "medium"
    },
    {
      "id" : "os_malicious_code_prevention",
      "title" : "Ensure the System Implements Malicious Code Protection Mechanisms",
      "severity" : "medium"
    },
    {
      "id" : "os_obscure_password",
      "title" : "Obscure Passwords",
      "severity" : "medium"
    },
    {
      "id" : "os_predictable_behavior",
      "title" : "Must behave in predictable and documented manner",
      "severity" : "medium"
    },
    {
      "id" : "os_prevent_priv_execution",
      "title" : "Prevent Software From Executing at Higher Privilege Levels than Users Executing The Software",
      "severity" : "medium"
    },
    {
      "id" : "os_prevent_priv_functions",
      "title" : "Configure the System to Block Non-Privileged Users from Executing Privileged Functions",
      "severity" : "medium"
    },
    {
      "id" : "os_prevent_unauthorized_disclosure",
      "title" : "Configure the System to Prevent the Unauthorized Disclosure of Data via Shared Resources",
      "severity" : "medium"
    },
    {
      "id" : "os_prohibit_remote_activation_collab_devices",
      "title" : "Prohibit Remote Activation of Collaborative Computing Devices",
      "severity" : "medium"
    },
    {
      "id" : "os_provide_disconnect_remote_access",
      "title" : "Provide Ability to Disconnect or Disable Remote Access",
      "severity" : "medium"
    },
    {
      "id" : "os_reauth_privilege",
      "title" : "Require users to reauthenticate for privilege escalation",
      "severity" : "medium"
    },
    {
      "id" : "os_reauth_users_change_authenticators",
      "title" : "Require users to reauthenticate when changing authenticators",
      "severity" : "medium"
    },
    {
      "id" : "os_remove_software_components_after_updates",
      "title" : "Must remove all software components after updated versions installed",
      "severity" : "medium"
    },
    {
      "id" : "os_required_crypto_module",
      "title" : "Ensure all Federal Laws, Executive Orders, Directives, Policies, Regulations, Standards, and Guidance for Authentication to a Cryptographic Module are Met",
      "severity" : "medium"
    },
    {
      "id" : "os_secure_enclave",
      "title" : "Protected Storage for Cryptographic Keys",
      "severity" : "medium"
    },
    {
      "id" : "os_separate_functionality",
      "title" : "Configure the System to Separate User and System Functionality",
      "severity" : "medium"
    },
    {
      "id" : "os_store_encrypted_passwords",
      "title" : "Encrypt Stored Passwords",
      "severity" : "medium"
    },
    {
      "id" : "os_unique_identification",
      "title" : "Uniquely Identify Users and Processes",
      "severity" : "medium"
    },
    {
      "id" : "os_verify_remote_disconnection",
      "title" : "Verify remote disconnection of sessions",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_force_password_change",
      "title" : "Force Password Change at Next Logon",
      "severity" : "medium"
    },
    {
      "id" : "audit_off_load_records",
      "title" : "Off-Load Audit Records",
      "severity" : "medium"
    },
    {
      "id" : "os_auth_peripherals",
      "title" : "Must Authenticate Before Establishing a Connection",
      "severity" : "medium"
    },
    {
      "id" : "os_continuous_monitoring",
      "title" : "Configure Automated Flaw Remediation",
      "severity" : "medium"
    },
    {
      "id" : "os_protect_dos_attacks",
      "title" : "Protect Against Denial of Service Attacks by Ensuring Rate-Limiting Measures on Network Interfaces",
      "severity" : "medium"
    },
    {
      "id" : "os_reauth_devices_change_authenticators",
      "title" : "Require Devices to Reauthenticate when Changing Authenticators",
      "severity" : "medium"
    },
    {
      "id" : "os_secure_name_resolution",
      "title" : "Secure Name Address Resolution Service",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_wifi_disable_when_connected_to_ethernet",
      "title" : "Disable Wi-Fi When Connected to Ethernet",
      "severity" : "medium"
    },
    {
      "id" : "os_access_control_mobile_devices",
      "title" : "Access Control for Mobile Devices",
      "severity" : "medium"
    },
    {
      "id" : "os_identify_non-org_users",
      "title" : "Configure the System to Uniquely Identify and Authenticate Non-Organizational Users",
      "severity" : "medium"
    },
    {
      "id" : "os_information_validation",
      "title" : "Information Input Validation",
      "severity" : "medium"
    },
    {
      "id" : "os_managed_access_control_points",
      "title" : "Managed Access Control Points",
      "severity" : "medium"
    },
    {
      "id" : "os_nonlocal_maintenance",
      "title" : "Configure the System for Non-local Maintenance",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_controls",
      "title" : "Out of Scope Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_filevault",
      "title" : "FileVault Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_firewall_pf",
      "title" : "Packet Filter (pf) Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_password_policy",
      "title" : "Password Policy Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_smartcard",
      "title" : "Smartcard Supplemental",
      "severity" : "medium"
    }
  ]

  enabled_rules = {
    for rule in local.all_rules :
    rule.id => rule
    if !contains(var.disabled_rules, rule.id) && !contains(keys(var.exemptions), rule.id)
  }
}

# ---------------------------------------------------------------------------
# Device group — targets macOS 26 devices
# ---------------------------------------------------------------------------
resource "jamfplatform_device_group" "this" {
  name        = "${var.baseline_display_name} — macOS ${var.macos_version}"
  group_type  = "smart"
  device_type = "computer"
  criteria = [{
    criteria = "Operating System Version"
    operator = "greater than or equal"
    value    = var.macos_version_min
  }]
}

# ---------------------------------------------------------------------------
# Compliance Benchmark Engine — rule metadata from mSCP
# ---------------------------------------------------------------------------
data "jamfplatform_cbengine_rules" "this" {
  baseline_id = var.baseline_id
}

# ---------------------------------------------------------------------------
# Benchmark resource — all rules enabled by default, with per-rule overrides
# ---------------------------------------------------------------------------
resource "jamfplatform_cbengine_benchmark" "this" {
  title              = var.baseline_display_name
  description        = "${var.baseline_display_name} — mSCP ${var.mscp_branch} @ ${var.mscp_revision} — Managed by Terraform"
  source_baseline_id = var.baseline_id

  sources = [for s in data.jamfplatform_cbengine_rules.this.sources : {
    branch   = s.branch
    revision = s.revision
  }]

  rules = [
    for r in data.jamfplatform_cbengine_rules.this.rules : {
      id        = r.id
      enabled   = contains(keys(local.enabled_rules), r.id)
      odv_value = try(var.rule_overrides[r.id].odv_value, null)
    }
  ]

  target_device_group = jamfplatform_device_group.this.id
  enforcement_mode    = var.enforcement_mode
}
