# Compliance Baseline: NIST SP 800-171 Rev 3
# macOS 26 (26.0+)
# mSCP branch: tahoe  revision: rev3.0
# Generated by scripts/generate_tf_compliance.py — DO NOT EDIT DIRECTLY

locals {
  # All rules for this baseline (id, title, severity)
  all_rules = [
    {
      "id" : "audit_acls_files_configure",
      "title" : "Configure Audit Log Files to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_acls_folders_configure",
      "title" : "Configure Audit Log Folder to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_auditd_enabled",
      "title" : "Enable Security Auditing",
      "severity" : "medium"
    },
    {
      "id" : "audit_failure_halt",
      "title" : "Configure System to Shut Down Upon Audit Failure",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_group_configure",
      "title" : "Configure Audit Log Files Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_mode_configure",
      "title" : "Configure Audit Log Files to Mode 440 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_owner_configure",
      "title" : "Configure Audit Log Files to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_aa_configure",
      "title" : "Configure System to Audit All Authorization and Authentication Events",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_ad_configure",
      "title" : "Configure System to Audit All Administrative Action Events",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_ex_configure",
      "title" : "Configure System to Audit All Failed Program Execution on the System",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_fm_failed_configure",
      "title" : "Configure System to Audit All Failed Change of Object Attributes",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_fr_configure",
      "title" : "Configure System to Audit All Failed Read Actions on the System",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_fw_configure",
      "title" : "Configure System to Audit All Failed Write Actions on the System",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_lo_configure",
      "title" : "Configure System to Audit All Log In and Log Out Events",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_group_configure",
      "title" : "Configure Audit Log Folders Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_owner_configure",
      "title" : "Configure Audit Log Folders to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_folders_mode_configure",
      "title" : "Configure Audit Log Folders to Mode 700 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_retention_configure",
      "title" : "Configure Audit Retention to $ODV",
      "severity" : "low"
    },
    {
      "id" : "audit_settings_failure_notify",
      "title" : "Configure Audit Failure Notification",
      "severity" : "medium"
    },
    {
      "id" : "auth_pam_login_smartcard_enforce",
      "title" : "Enforce Multifactor Authentication for Login",
      "severity" : "medium"
    },
    {
      "id" : "auth_pam_su_smartcard_enforce",
      "title" : "Enforce Multifactor Authentication for the su Command",
      "severity" : "medium"
    },
    {
      "id" : "auth_pam_sudo_smartcard_enforce",
      "title" : "Enforce Multifactor Authentication for Privilege Escalation Through the sudo Command",
      "severity" : "medium"
    },
    {
      "id" : "auth_smartcard_allow",
      "title" : "Allow Smartcard Authentication",
      "severity" : "medium"
    },
    {
      "id" : "auth_smartcard_enforce",
      "title" : "Enforce Smartcard Authentication",
      "severity" : "medium"
    },
    {
      "id" : "auth_ssh_password_authentication_disable",
      "title" : "Disable Password Authentication for SSH",
      "severity" : "high"
    },
    {
      "id" : "icloud_addressbook_disable",
      "title" : "Disable iCloud Address Book",
      "severity" : "medium"
    },
    {
      "id" : "icloud_appleid_system_settings_disable",
      "title" : "Disable the System Setting for Apple ID",
      "severity" : "high"
    },
    {
      "id" : "icloud_bookmarks_disable",
      "title" : "Disable iCloud Bookmarks",
      "severity" : "medium"
    },
    {
      "id" : "icloud_calendar_disable",
      "title" : "Disable the iCloud Calendar Services",
      "severity" : "medium"
    },
    {
      "id" : "icloud_drive_disable",
      "title" : "Disable iCloud Document Sync",
      "severity" : "medium"
    },
    {
      "id" : "icloud_freeform_disable",
      "title" : "Disable the iCloud Freeform Services",
      "severity" : "medium"
    },
    {
      "id" : "icloud_game_center_disable",
      "title" : "Disable iCloud Game Center",
      "severity" : "medium"
    },
    {
      "id" : "icloud_keychain_disable",
      "title" : "Disable iCloud Keychain Sync",
      "severity" : "medium"
    },
    {
      "id" : "icloud_mail_disable",
      "title" : "Disable iCloud Mail",
      "severity" : "medium"
    },
    {
      "id" : "icloud_notes_disable",
      "title" : "Disable iCloud Notes",
      "severity" : "medium"
    },
    {
      "id" : "icloud_photos_disable",
      "title" : "Disable iCloud Photo Library",
      "severity" : "medium"
    },
    {
      "id" : "icloud_private_relay_disable",
      "title" : "Disable iCloud Private Relay",
      "severity" : "medium"
    },
    {
      "id" : "icloud_reminders_disable",
      "title" : "Disable iCloud Reminders",
      "severity" : "medium"
    },
    {
      "id" : "icloud_sync_disable",
      "title" : "Disable iCloud Desktop and Document Folder Sync",
      "severity" : "medium"
    },
    {
      "id" : "os_account_modification_disable",
      "title" : "Disable AppleID and Internet Account Modifications",
      "severity" : "medium"
    },
    {
      "id" : "os_airdrop_disable",
      "title" : "Disable AirDrop",
      "severity" : "medium"
    },
    {
      "id" : "os_appleid_prompt_disable",
      "title" : "Disable Apple ID Setup during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_authenticated_root_enable",
      "title" : "Enable Authenticated Root",
      "severity" : "medium"
    },
    {
      "id" : "os_bonjour_disable",
      "title" : "Disable Bonjour Multicast",
      "severity" : "medium"
    },
    {
      "id" : "os_burn_support_disable",
      "title" : "Disable Burn Support",
      "severity" : "low"
    },
    {
      "id" : "os_config_profile_ui_install_disable",
      "title" : "Disable Installation of Configuration Profiles through the User Interface",
      "severity" : "medium"
    },
    {
      "id" : "os_dictation_disable",
      "title" : "Disable Dictation",
      "severity" : "medium"
    },
    {
      "id" : "os_erase_content_and_settings_disable",
      "title" : "Disable Erase Content and Settings",
      "severity" : "medium"
    },
    {
      "id" : "os_filevault_autologin_disable",
      "title" : "Disable FileVault Automatic Login",
      "severity" : "medium"
    },
    {
      "id" : "os_firewall_default_deny_require",
      "title" : "Control Connections to Other Systems via a Deny-All and Allow-by-Exception Firewall Policy",
      "severity" : "medium"
    },
    {
      "id" : "os_firmware_password_require",
      "title" : "Enable Firmware Password",
      "severity" : "medium"
    },
    {
      "id" : "os_gatekeeper_enable",
      "title" : "Enable Gatekeeper",
      "severity" : "high"
    },
    {
      "id" : "os_genmoji_disable",
      "title" : "Disable Genmoji AI Creation",
      "severity" : "medium"
    },
    {
      "id" : "os_handoff_disable",
      "title" : "Disable Handoff",
      "severity" : "medium"
    },
    {
      "id" : "os_home_folders_secure",
      "title" : "Secure User's Home Folders",
      "severity" : "medium"
    },
    {
      "id" : "os_httpd_disable",
      "title" : "Disable the Built-in Web Server",
      "severity" : "medium"
    },
    {
      "id" : "os_icloud_storage_prompt_disable",
      "title" : "Disable iCloud Storage Setup during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_image_playground_disable",
      "title" : "Disable Apple Intelligence Image Playground",
      "severity" : "medium"
    },
    {
      "id" : "os_iphone_mirroring_disable",
      "title" : "Disable iPhone Mirroring",
      "severity" : "medium"
    },
    {
      "id" : "os_ir_support_disable",
      "title" : "Disable Infrared (IR) support",
      "severity" : "medium"
    },
    {
      "id" : "os_loginwindow_adminhostinfo_disabled",
      "title" : "Prevent AdminHostInfo from Being Available at Login Window",
      "severity" : "medium"
    },
    {
      "id" : "os_mail_smart_reply_disable",
      "title" : "Disable Apple Intelligence Mail Smart Replies",
      "severity" : "medium"
    },
    {
      "id" : "os_mail_summary_disable",
      "title" : "Disable Apple Intelligence Mail Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_mdm_require",
      "title" : "Enforce Enrollment in Mobile Device Management",
      "severity" : "medium"
    },
    {
      "id" : "os_nfsd_disable",
      "title" : "Disable Network File System Service",
      "severity" : "medium"
    },
    {
      "id" : "os_notes_transcription_disable",
      "title" : "Disable Apple Intelligence Notes Transcription",
      "severity" : "medium"
    },
    {
      "id" : "os_notes_transcription_summary_disable",
      "title" : "Disable Apple Intelligence Notes Transcription Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_on_device_dictation_enforce",
      "title" : "Enforce On Device Dictation",
      "severity" : "medium"
    },
    {
      "id" : "os_password_proximity_disable",
      "title" : "Disable Proximity Based Password Sharing Requests",
      "severity" : "medium"
    },
    {
      "id" : "os_password_sharing_disable",
      "title" : "Disable Password Sharing",
      "severity" : "medium"
    },
    {
      "id" : "os_photos_enhanced_search_disable",
      "title" : "Disable Photos Enhanced Visual Search",
      "severity" : "medium"
    },
    {
      "id" : "os_policy_banner_loginwindow_enforce",
      "title" : "Display Policy Banner at Login Window",
      "severity" : "medium"
    },
    {
      "id" : "os_policy_banner_ssh_configure",
      "title" : "Display Policy Banner at Remote Login",
      "severity" : "medium"
    },
    {
      "id" : "os_policy_banner_ssh_enforce",
      "title" : "Enforce SSH to Display Policy Banner",
      "severity" : "medium"
    },
    {
      "id" : "os_privacy_setup_prompt_disable",
      "title" : "Disable Privacy Setup Services During Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_recovery_lock_enable",
      "title" : "Enable Recovery Lock",
      "severity" : "medium"
    },
    {
      "id" : "os_root_disable",
      "title" : "Disable Root Login",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_reader_summary_disable",
      "title" : "Disable Apple Intelligence Safari Reader Summary",
      "severity" : "medium"
    },
    {
      "id" : "os_screensaver_loginwindow_enforce",
      "title" : "Enforce Screen Saver at Login Window",
      "severity" : "medium"
    },
    {
      "id" : "os_sip_enable",
      "title" : "Ensure System Integrity Protection is Enabled",
      "severity" : "high"
    },
    {
      "id" : "os_siri_prompt_disable",
      "title" : "Disable Siri Setup during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_skip_apple_intelligence_enable",
      "title" : "Disable Apple Intelligence During Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_skip_screen_time_prompt_enable",
      "title" : "Disable Screen Time Prompt During Setup Assistant",
      "severity" : "low"
    },
    {
      "id" : "os_skip_unlock_with_watch_enable",
      "title" : "Disable Unlock with Apple Watch During Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_ssh_fips_compliant",
      "title" : "Limit SSH to FIPS Compliant Connections",
      "severity" : "high"
    },
    {
      "id" : "os_ssh_server_alive_count_max_configure",
      "title" : "Set SSH Active Server Alive Maximum to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_ssh_server_alive_interval_configure",
      "title" : "Configure SSH ServerAliveInterval option set to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_channel_timeout_configure",
      "title" : "Configure SSHD Channel Timeout to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_client_alive_count_max_configure",
      "title" : "Configure SSHD ClientAliveCountMax to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_client_alive_interval_configure",
      "title" : "Configure SSHD ClientAliveInterval to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sshd_fips_compliant",
      "title" : "Limit SSHD to FIPS Compliant Connections",
      "severity" : "high"
    },
    {
      "id" : "os_sshd_unused_connection_timeout_configure",
      "title" : "Configure SSHD Unused Connection Timeout to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sudo_log_enforce",
      "title" : "Configure Sudo To Log Events",
      "severity" : "medium"
    },
    {
      "id" : "os_sudoers_timestamp_type_configure",
      "title" : "Configure Sudoers Timestamp Type",
      "severity" : "medium"
    },
    {
      "id" : "os_tftpd_disable",
      "title" : "Disable Trivial File Transfer Protocol Service",
      "severity" : "high"
    },
    {
      "id" : "os_time_server_enabled",
      "title" : "Enable Time Synchronization Daemon",
      "severity" : "medium"
    },
    {
      "id" : "os_touchid_prompt_disable",
      "title" : "Disable TouchID Prompt during Setup Assistant",
      "severity" : "medium"
    },
    {
      "id" : "os_unlock_active_user_session_disable",
      "title" : "Disable Login to Other User's Active and Locked Sessions",
      "severity" : "medium"
    },
    {
      "id" : "os_uucp_disable",
      "title" : "Disable Unix-to-Unix Copy Protocol Service",
      "severity" : "medium"
    },
    {
      "id" : "os_writing_tools_disable",
      "title" : "Disable Apple Intelligence Writing Tools",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_account_inactivity_enforce",
      "title" : "Disable Accounts after $ODV Days of Inactivity",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_account_lockout_enforce",
      "title" : "Limit Consecutive Failed Login Attempts to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_account_lockout_timeout_enforce",
      "title" : "Set Account Lockout Time to $ODV Minutes",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_history_enforce",
      "title" : "Prohibit Password Reuse for a Minimum of $ODV Generations",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_minimum_length_enforce",
      "title" : "Require a Minimum Password Length of $ODV Characters",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_simple_sequence_disable",
      "title" : "Prohibit Repeating, Ascending, and Descending Character Sequences",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_apple_watch_unlock_disable",
      "title" : "Prevent Apple Watch from Terminating a Session Lock",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_automatic_login_disable",
      "title" : "Disable Unattended or Automatic Logon to the System",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_automatic_logout_enforce",
      "title" : "Enforce Auto Logout After $ODV Seconds of Inactivity",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_bluetooth_disable",
      "title" : "Disable Bluetooth When no Approved Device is Connected",
      "severity" : "high"
    },
    {
      "id" : "system_settings_bluetooth_sharing_disable",
      "title" : "Disable Bluetooth Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_content_caching_disable",
      "title" : "Disable Content Caching Service",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_diagnostics_reports_disable",
      "title" : "Disable Sending Diagnostic and Usage Data to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_external_intelligence_disable",
      "title" : "Disable External Intelligence Integrations",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_external_intelligence_sign_in_disable",
      "title" : "Disable External Intelligence Integration Sign In",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_filevault_enforce",
      "title" : "Enforce FileVault",
      "severity" : "high"
    },
    {
      "id" : "system_settings_find_my_disable",
      "title" : "Disable Find My Service",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_firewall_enable",
      "title" : "Enable macOS Application Firewall",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_firewall_stealth_mode_enable",
      "title" : "Enable Firewall Stealth Mode",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_gatekeeper_identified_developers_allowed",
      "title" : "Apply Gatekeeper Settings to Block Applications from Unidentified Developers",
      "severity" : "high"
    },
    {
      "id" : "system_settings_gatekeeper_override_disallow",
      "title" : "Configure Gatekeeper to Disallow End User Override",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_access_smb_disable",
      "title" : "Disable Guest Access to Shared SMB Folders",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_account_disable",
      "title" : "Disable the Guest Account",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_hot_corners_disable",
      "title" : "Disable Hot Corners",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_assistive_voice_disable",
      "title" : "Disable Sending Audio Recordings and Transcripts to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_search_disable",
      "title" : "Disable Improve Search Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_siri_dictation_disable",
      "title" : "Disable Improve Siri and Dictation Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_internet_accounts_disable",
      "title" : "Disable the Internet Accounts System Preference Pane",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_internet_sharing_disable",
      "title" : "Disable Internet Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_location_services_disable",
      "title" : "Disable Location Services",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_loginwindow_prompt_username_password_enforce",
      "title" : "Configure Login Window to Prompt for Username and Password",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_media_sharing_disabled",
      "title" : "Disable Media Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_password_hints_disable",
      "title" : "Disable Password Hints",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_personalized_advertising_disable",
      "title" : "Disable Personalized Advertising",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_rae_disable",
      "title" : "Disable Remote Apple Events",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screen_sharing_disable",
      "title" : "Disable Screen Sharing and Apple Remote Desktop",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_ask_for_password_delay_enforce",
      "title" : "Enforce Session Lock After Screen Saver is Started",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_password_enforce",
      "title" : "Enforce Screen Saver Password",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_timeout_enforce",
      "title" : "Enforce Screen Saver Timeout",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_siri_disable",
      "title" : "Disable Siri",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_smbd_disable",
      "title" : "Disable Server Message Block Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_softwareupdate_current",
      "title" : "Ensure Software Update is Updated and Current",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_ssh_disable",
      "title" : "Disable SSH Server for Remote Access Sessions",
      "severity" : "high"
    },
    {
      "id" : "system_settings_ssh_enable",
      "title" : "Enable SSH Server for Remote Access Sessions",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_system_wide_preferences_configure",
      "title" : "Require Administrator Password to Modify System-Wide Preferences",
      "severity" : "high"
    },
    {
      "id" : "system_settings_time_server_configure",
      "title" : "Configure macOS to Use an Authorized Time Server",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_time_server_enforce",
      "title" : "Enforce macOS Time Synchronization",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_token_removal_enforce",
      "title" : "Configure User Session Lock When a Smart Token is Removed",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_touchid_unlock_disable",
      "title" : "Disable TouchID for Unlocking the Device",
      "severity" : "medium"
    },
    {
      "id" : "os_implement_cryptography",
      "title" : "Configure the System to Implement Approved Cryptography to Protect Information",
      "severity" : "medium"
    },
    {
      "id" : "os_logical_access",
      "title" : "Enforce Approved Authorization for Logical Access",
      "severity" : "medium"
    },
    {
      "id" : "os_malicious_code_prevention",
      "title" : "Ensure the System Implements Malicious Code Protection Mechanisms",
      "severity" : "medium"
    },
    {
      "id" : "os_obscure_password",
      "title" : "Obscure Passwords",
      "severity" : "medium"
    },
    {
      "id" : "os_prevent_priv_functions",
      "title" : "Configure the System to Block Non-Privileged Users from Executing Privileged Functions",
      "severity" : "medium"
    },
    {
      "id" : "os_prevent_unauthorized_disclosure",
      "title" : "Configure the System to Prevent the Unauthorized Disclosure of Data via Shared Resources",
      "severity" : "medium"
    },
    {
      "id" : "os_prohibit_remote_activation_collab_devices",
      "title" : "Prohibit Remote Activation of Collaborative Computing Devices",
      "severity" : "medium"
    },
    {
      "id" : "os_reauth_privilege",
      "title" : "Require users to reauthenticate for privilege escalation",
      "severity" : "medium"
    },
    {
      "id" : "os_reauth_users_change_authenticators",
      "title" : "Require users to reauthenticate when changing authenticators",
      "severity" : "medium"
    },
    {
      "id" : "os_separate_functionality",
      "title" : "Configure the System to Separate User and System Functionality",
      "severity" : "medium"
    },
    {
      "id" : "os_store_encrypted_passwords",
      "title" : "Encrypt Stored Passwords",
      "severity" : "medium"
    },
    {
      "id" : "os_unique_identification",
      "title" : "Uniquely Identify Users and Processes",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_force_password_change",
      "title" : "Force Password Change at Next Logon",
      "severity" : "medium"
    },
    {
      "id" : "os_reauth_devices_change_authenticators",
      "title" : "Require Devices to Reauthenticate when Changing Authenticators",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_50_percent",
      "title" : "Require a Minimum of Fifty Percent Character Change in New Passwords",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_wifi_disable_when_connected_to_ethernet",
      "title" : "Disable Wi-Fi When Connected to Ethernet",
      "severity" : "medium"
    },
    {
      "id" : "os_access_control_mobile_devices",
      "title" : "Access Control for Mobile Devices",
      "severity" : "medium"
    },
    {
      "id" : "os_nonlocal_maintenance",
      "title" : "Configure the System for Non-local Maintenance",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_controls",
      "title" : "Out of Scope Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_filevault",
      "title" : "FileVault Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_firewall_pf",
      "title" : "Packet Filter (pf) Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_password_policy",
      "title" : "Password Policy Supplemental",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_smartcard",
      "title" : "Smartcard Supplemental",
      "severity" : "medium"
    }
  ]

  enabled_rules = {
    for rule in local.all_rules :
    rule.id => rule
    if !contains(var.disabled_rules, rule.id) && !contains(keys(var.exemptions), rule.id)
  }
}

# ---------------------------------------------------------------------------
# Device group — targets macOS 26 devices
# ---------------------------------------------------------------------------
resource "jamfplatform_device_group" "this" {
  name        = "${var.baseline_display_name} — macOS ${var.macos_version}"
  group_type  = "smart"
  device_type = "computer"
  criteria = [{
    criteria = "Operating System Version"
    operator = "greater than or equal"
    value    = var.macos_version_min
  }]
}

# ---------------------------------------------------------------------------
# Compliance Benchmark Engine — rule metadata from mSCP
# ---------------------------------------------------------------------------
data "jamfplatform_cbengine_rules" "this" {
  baseline_id = var.baseline_id
}

# ---------------------------------------------------------------------------
# Benchmark resource — all rules enabled by default, with per-rule overrides
# ---------------------------------------------------------------------------
resource "jamfplatform_cbengine_benchmark" "this" {
  title              = var.baseline_display_name
  description        = "${var.baseline_display_name} — mSCP ${var.mscp_branch} @ ${var.mscp_revision} — Managed by Terraform"
  source_baseline_id = var.baseline_id

  sources = [for s in data.jamfplatform_cbengine_rules.this.sources : {
    branch   = s.branch
    revision = s.revision
  }]

  rules = [
    for r in data.jamfplatform_cbengine_rules.this.rules : {
      id        = r.id
      enabled   = contains(keys(local.enabled_rules), r.id)
      odv_value = try(var.rule_overrides[r.id].odv_value, null)
    }
  ]

  target_device_group = jamfplatform_device_group.this.id
  enforcement_mode    = var.enforcement_mode
}
