# Variables for NIST SP 800-53 Rev 5 — Privacy — macOS 14
# NOTE: This baseline awaits upstream mSCP publication.
# Generated by scripts/generate_tf_compliance.py — DO NOT EDIT DIRECTLY

variable "enforcement_mode" {
  type        = string
  default     = "MONITOR"
  description = "Enforcement mode for the compliance benchmark"

  validation {
    condition     = contains(["MONITOR", "MONITOR_AND_ENFORCE"], var.enforcement_mode)
    error_message = "enforcement_mode must be MONITOR or MONITOR_AND_ENFORCE"
  }
}

variable "disabled_rules" {
  type        = list(string)
  default     = []
  description = "Rule IDs to permanently disable"
}

variable "rule_overrides" {
  type = map(object({
    odv_value = optional(string)
  }))
  default     = {}
  description = "Organization-Defined Value (ODV) overrides per rule"
}

variable "exemptions" {
  type = map(object({
    reason                = string
    ticket                = optional(string)
    risk_status           = string
    compensating_controls = optional(string)
    reviewer              = optional(string)
    review_date           = optional(string)
    expires               = optional(string)
  }))
  default     = {}
  description = "Exemptions with audit justification for compliance tracking"

  validation {
    condition = alltrue([
      for k, v in var.exemptions :
      contains(["ACCEPTED", "TEMPORARY", "ACCEPTED_WITH_COMPENSATING_CONTROLS", "UNDER_REVIEW"], v.risk_status)
    ])
    error_message = "risk_status must be one of: ACCEPTED, TEMPORARY, ACCEPTED_WITH_COMPENSATING_CONTROLS, UNDER_REVIEW"
  }
}

variable "baseline_id" {
  type        = string
  default     = "800-53r5_privacy"
  description = "mSCP baseline identifier"
}

variable "baseline_display_name" {
  type        = string
  default     = "NIST SP 800-53 Rev 5 — Privacy"
  description = "Human-readable baseline name"
}

variable "mscp_branch" {
  type        = string
  default     = "sonoma"
  description = "mSCP git branch for this macOS version"
}

variable "mscp_revision" {
  type        = string
  default     = "pending_upstream"
  description = "mSCP release revision (tag)"
}

variable "macos_version" {
  type        = string
  default     = "14"
  description = "macOS major version number"
}

variable "macos_version_min" {
  type        = string
  default     = "14.0"
  description = "Minimum macOS version for device group targeting"
}

variable "rule_count" {
  type        = number
  default     = 0
  description = "Number of rules in this baseline"
}
