# Compliance Baseline: Netherlands BIO — Plus
# macOS 14 (14.0+)
# mSCP branch: sonoma  revision: rev2.0
# Generated by scripts/generate_tf_compliance.py — DO NOT EDIT DIRECTLY

locals {
  # All rules for this baseline (id, title, severity)
  all_rules = [
    {
      "id" : "audit_acls_files_configure",
      "title" : "Configure Audit Log Files to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_acls_folders_configure",
      "title" : "Configure Audit Log Folder to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_auditd_enabled",
      "title" : "Enable Security Auditing",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_acls_configure",
      "title" : "Configure Audit_Control to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_group_configure",
      "title" : "Configure Audit_Control Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_mode_configure",
      "title" : "Configure Audit_Control Owner to Mode 440 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_owner_configure",
      "title" : "Configure Audit_Control Owner to Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_group_configure",
      "title" : "Configure Audit Log Files Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_mode_configure",
      "title" : "Configure Audit Log Files to Mode 440 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_owner_configure",
      "title" : "Configure Audit Log Files to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_ad_configure",
      "title" : "Configure System to Audit All Administrative Action Events",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_group_configure",
      "title" : "Configure Audit Log Folders Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_owner_configure",
      "title" : "Configure Audit Log Folders to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_folders_mode_configure",
      "title" : "Configure Audit Log Folders to Mode 700 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_retention_configure",
      "title" : "Configure Audit Retention to $ODV",
      "severity" : "low"
    },
    {
      "id" : "icloud_drive_disable",
      "title" : "Disable iCloud Document Sync",
      "severity" : "medium"
    },
    {
      "id" : "icloud_keychain_disable",
      "title" : "Disable iCloud Keychain Sync",
      "severity" : "medium"
    },
    {
      "id" : "icloud_sync_disable",
      "title" : "Disable iCloud Desktop and Document Folder Sync",
      "severity" : "medium"
    },
    {
      "id" : "os_anti_virus_installed",
      "title" : "Must Use an Approved Antivirus Program",
      "severity" : "high"
    },
    {
      "id" : "os_authenticated_root_enable",
      "title" : "Enable Authenticated Root",
      "severity" : "medium"
    },
    {
      "id" : "os_external_storage_access_defined",
      "title" : "Access to External Storage Must Be Defined",
      "severity" : "medium"
    },
    {
      "id" : "os_gatekeeper_enable",
      "title" : "Enable Gatekeeper",
      "severity" : "high"
    },
    {
      "id" : "os_home_folders_secure",
      "title" : "Secure User's Home Folders",
      "severity" : "medium"
    },
    {
      "id" : "os_httpd_disable",
      "title" : "Disable the Built-in Web Server",
      "severity" : "medium"
    },
    {
      "id" : "os_install_log_retention_configure",
      "title" : "Configure Install.log Retention to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_mdm_require",
      "title" : "Enforce Enrollment in Mobile Device Management",
      "severity" : "medium"
    },
    {
      "id" : "os_nfsd_disable",
      "title" : "Disable Network File System Service",
      "severity" : "medium"
    },
    {
      "id" : "os_on_device_dictation_enforce",
      "title" : "Enforce On Device Dictation",
      "severity" : "medium"
    },
    {
      "id" : "os_password_hint_remove",
      "title" : "Remove Password Hint From User Accounts",
      "severity" : "medium"
    },
    {
      "id" : "os_password_proximity_disable",
      "title" : "Disable Proximity Based Password Sharing Requests",
      "severity" : "medium"
    },
    {
      "id" : "os_password_sharing_disable",
      "title" : "Disable Password Sharing",
      "severity" : "medium"
    },
    {
      "id" : "os_root_disable",
      "title" : "Disable Root Login",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_advertising_privacy_protection_enable",
      "title" : "Ensure Advertising Privacy Protection in Safari Is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_open_safe_downloads_disable",
      "title" : "Disable Automatic Opening of Safe Files in Safari",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_prevent_cross-site_tracking_enable",
      "title" : "Ensure Prevent Cross-site Tracking in Safari Is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_show_full_website_address_enable",
      "title" : "Ensure Show Full Website Address in Safari Is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_show_status_bar_enabled",
      "title" : "Ensure Show Safari shows the Status Bar is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_warn_fraudulent_website_enable",
      "title" : "Ensure Warn When Visiting A Fraudulent Website in Safari Is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_secure_boot_verify",
      "title" : "Ensure Secure Boot Level Set to Full",
      "severity" : "medium"
    },
    {
      "id" : "os_setup_assistant_filevault_enforce",
      "title" : "Enforce FileVault in Setup Assistant",
      "severity" : "high"
    },
    {
      "id" : "os_sip_enable",
      "title" : "Ensure System Integrity Protection is Enabled",
      "severity" : "high"
    },
    {
      "id" : "os_software_update_app_update_enforce",
      "title" : "Enforce Software Update App Update Updates Automatically",
      "severity" : "medium"
    },
    {
      "id" : "os_sudo_log_enforce",
      "title" : "Configure Sudo To Log Events",
      "severity" : "medium"
    },
    {
      "id" : "os_sudo_timeout_configure",
      "title" : "Configure Sudo Timeout Period to $ODV",
      "severity" : "medium"
    },
    {
      "id" : "os_sudoers_timestamp_type_configure",
      "title" : "Configure Sudoers Timestamp Type",
      "severity" : "medium"
    },
    {
      "id" : "os_terminal_secure_keyboard_enable",
      "title" : "Ensure Secure Keyboard Entry Terminal.app is Enabled",
      "severity" : "medium"
    },
    {
      "id" : "os_tftpd_disable",
      "title" : "Disable Trivial File Transfer Protocol Service",
      "severity" : "high"
    },
    {
      "id" : "os_time_server_enabled",
      "title" : "Enable Time Synchronization Daemon",
      "severity" : "medium"
    },
    {
      "id" : "os_unlock_active_user_session_disable",
      "title" : "Disable Login to Other User's Active and Locked Sessions",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_minimum_length_enforce",
      "title" : "Require a Minimum Password Length of $ODV Characters",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_automatic_login_disable",
      "title" : "Disable Unattended or Automatic Logon to the System",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_background_security_improvement_removal_disable",
      "title" : "Disable rollback of Background Security Improvements using DDM.",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_diagnostics_reports_disable",
      "title" : "Disable Sending Diagnostic and Usage Data to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_download_software_update_enforce",
      "title" : "Enforce Software Update Downloads Updates Automatically using DDM.",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_external_intelligence_sign_in_disable",
      "title" : "Disable External Intelligence Integration Sign In",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_filevault_enforce",
      "title" : "Enforce FileVault",
      "severity" : "high"
    },
    {
      "id" : "system_settings_find_my_disable",
      "title" : "Disable Find My Service",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_firewall_enable",
      "title" : "Enable macOS Application Firewall",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_firewall_stealth_mode_enable",
      "title" : "Enable Firewall Stealth Mode",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_gatekeeper_identified_developers_allowed",
      "title" : "Apply Gatekeeper Settings to Block Applications from Unidentified Developers",
      "severity" : "high"
    },
    {
      "id" : "system_settings_gatekeeper_override_disallow",
      "title" : "Configure Gatekeeper to Disallow End User Override",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_account_disable",
      "title" : "Disable the Guest Account",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_assistive_voice_disable",
      "title" : "Disable Sending Audio Recordings and Transcripts to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_search_disable",
      "title" : "Disable Improve Search Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_improve_siri_dictation_disable",
      "title" : "Disable Improve Siri and Dictation Information to Apple",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_internet_sharing_disable",
      "title" : "Disable Internet Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_loginwindow_loginwindowtext_enable",
      "title" : "Configure Login Window to Show A Custom Message",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_macos_updates_install_enforce",
      "title" : "Enforce macOS Updates are Automatically Installed using DDM.",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_media_sharing_disabled",
      "title" : "Disable Media Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_password_hints_disable",
      "title" : "Disable Password Hints",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_personalized_advertising_disable",
      "title" : "Disable Personalized Advertising",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_printer_sharing_disable",
      "title" : "Disable Printer Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_rae_disable",
      "title" : "Disable Remote Apple Events",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_remote_management_disable",
      "title" : "Disable Remote Management",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screen_sharing_disable",
      "title" : "Disable Screen Sharing and Apple Remote Desktop",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_ask_for_password_delay_enforce",
      "title" : "Enforce Session Lock After Screen Saver is Started",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_password_enforce",
      "title" : "Enforce Screen Saver Password",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_screensaver_timeout_enforce",
      "title" : "Enforce Screen Saver Timeout",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_security_update_install",
      "title" : "Enforce Automatic Installs of Available Security Updates using DDM.",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_smbd_disable",
      "title" : "Disable Server Message Block Sharing",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_softwareupdate_current",
      "title" : "Ensure Software Update is Updated and Current",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_ssh_disable",
      "title" : "Disable SSH Server for Remote Access Sessions",
      "severity" : "high"
    },
    {
      "id" : "system_settings_system_wide_preferences_configure",
      "title" : "Require Administrator Password to Modify System-Wide Preferences",
      "severity" : "high"
    },
    {
      "id" : "system_settings_time_machine_encrypted_configure",
      "title" : "Ensure Time Machine Volumes are Encrypted",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_time_server_configure",
      "title" : "Configure macOS to Use an Authorized Time Server",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_time_server_enforce",
      "title" : "Enforce macOS Time Synchronization",
      "severity" : "medium"
    },
    {
      "id" : "os_secure_enclave",
      "title" : "Protected Storage for Cryptographic Keys",
      "severity" : "medium"
    },
    {
      "id" : "audit_off_load_records",
      "title" : "Off-Load Audit Records",
      "severity" : "medium"
    },
    {
      "id" : "os_provide_automated_account_management",
      "title" : "Employ Automated Mechanisms for Account Management Functions",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_filevault",
      "title" : "FileVault Supplemental",
      "severity" : "medium"
    }
  ]

  enabled_rules = {
    for rule in local.all_rules :
    rule.id => rule
    if !contains(var.disabled_rules, rule.id) && !contains(keys(var.exemptions), rule.id)
  }
}

# ---------------------------------------------------------------------------
# Device group — targets macOS 14 devices
# ---------------------------------------------------------------------------
resource "jamfplatform_device_group" "this" {
  name        = "${var.baseline_display_name} — macOS ${var.macos_version}"
  group_type  = "smart"
  device_type = "computer"
  criteria = [{
    criteria = "Operating System Version"
    operator = "greater than or equal"
    value    = var.macos_version_min
  }]
}

# ---------------------------------------------------------------------------
# Compliance Benchmark Engine — rule metadata from mSCP
# ---------------------------------------------------------------------------
data "jamfplatform_cbengine_rules" "this" {
  baseline_id = var.baseline_id
}

# ---------------------------------------------------------------------------
# Benchmark resource — all rules enabled by default, with per-rule overrides
# ---------------------------------------------------------------------------
resource "jamfplatform_cbengine_benchmark" "this" {
  title              = var.baseline_display_name
  description        = "${var.baseline_display_name} — mSCP ${var.mscp_branch} @ ${var.mscp_revision} — Managed by Terraform"
  source_baseline_id = var.baseline_id

  sources = [for s in data.jamfplatform_cbengine_rules.this.sources : {
    branch   = s.branch
    revision = s.revision
  }]

  rules = [
    for r in data.jamfplatform_cbengine_rules.this.rules : {
      id        = r.id
      enabled   = contains(keys(local.enabled_rules), r.id)
      odv_value = try(var.rule_overrides[r.id].odv_value, null)
    }
  ]

  target_device_group = jamfplatform_device_group.this.id
  enforcement_mode    = var.enforcement_mode
}
