# Compliance Baseline: Netherlands BIO — Base
# macOS 15 (15.0+)
# mSCP branch: sequoia  revision: rev4.0
# Generated by scripts/generate_tf_compliance.py — DO NOT EDIT DIRECTLY

locals {
  # All rules for this baseline (id, title, severity)
  all_rules = [
    {
      "id" : "audit_acls_files_configure",
      "title" : "Configure Audit Log Files to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_acls_folders_configure",
      "title" : "Configure Audit Log Folder to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_auditd_enabled",
      "title" : "Enable Security Auditing",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_acls_configure",
      "title" : "Configure Audit_Control to Not Contain Access Control Lists",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_group_configure",
      "title" : "Configure Audit_Control Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_mode_configure",
      "title" : "Configure Audit_Control Owner to Mode 440 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_control_owner_configure",
      "title" : "Configure Audit_Control Owner to Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_group_configure",
      "title" : "Configure Audit Log Files Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_mode_configure",
      "title" : "Configure Audit Log Files to Mode 440 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_files_owner_configure",
      "title" : "Configure Audit Log Files to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_flags_ad_configure",
      "title" : "Configure System to Audit All Administrative Action Events",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_group_configure",
      "title" : "Configure Audit Log Folders Group to Wheel",
      "severity" : "medium"
    },
    {
      "id" : "audit_folder_owner_configure",
      "title" : "Configure Audit Log Folders to be Owned by Root",
      "severity" : "medium"
    },
    {
      "id" : "audit_folders_mode_configure",
      "title" : "Configure Audit Log Folders to Mode 700 or Less Permissive",
      "severity" : "medium"
    },
    {
      "id" : "audit_retention_configure",
      "title" : "Configure Audit Retention to $ODV",
      "severity" : "low"
    },
    {
      "id" : "os_anti_virus_installed",
      "title" : "Must Use an Approved Antivirus Program",
      "severity" : "high"
    },
    {
      "id" : "os_config_data_install_enforce",
      "title" : "Enforce Installation of XProtect Remediator and Gatekeeper Updates Automatically",
      "severity" : "medium"
    },
    {
      "id" : "os_gatekeeper_enable",
      "title" : "Enable Gatekeeper",
      "severity" : "high"
    },
    {
      "id" : "os_mdm_require",
      "title" : "Enforce Enrollment in Mobile Device Management",
      "severity" : "medium"
    },
    {
      "id" : "os_safari_open_safe_downloads_disable",
      "title" : "Disable Automatic Opening of Safe Files in Safari",
      "severity" : "medium"
    },
    {
      "id" : "os_sip_enable",
      "title" : "Ensure System Integrity Protection is Enabled",
      "severity" : "high"
    },
    {
      "id" : "os_sudo_log_enforce",
      "title" : "Configure Sudo To Log Events",
      "severity" : "medium"
    },
    {
      "id" : "os_time_server_enabled",
      "title" : "Enable Time Synchronization Daemon",
      "severity" : "medium"
    },
    {
      "id" : "pwpolicy_minimum_length_enforce",
      "title" : "Require a Minimum Password Length of $ODV Characters",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_automatic_login_disable",
      "title" : "Disable Unattended or Automatic Logon to the System",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_critical_update_install_enforce",
      "title" : "Enforce Critical Security Updates to be Installed",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_filevault_enforce",
      "title" : "Enforce FileVault",
      "severity" : "high"
    },
    {
      "id" : "system_settings_find_my_disable",
      "title" : "Disable Find My Service",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_gatekeeper_identified_developers_allowed",
      "title" : "Apply Gatekeeper Settings to Block Applications from Unidentified Developers",
      "severity" : "high"
    },
    {
      "id" : "system_settings_gatekeeper_override_disallow",
      "title" : "Configure Gatekeeper to Disallow End User Override",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_guest_account_disable",
      "title" : "Disable the Guest Account",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_install_macos_updates_enforce",
      "title" : "Enforce macOS Updates are Automatically Installed",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_loginwindow_loginwindowtext_enable",
      "title" : "Configure Login Window to Show A Custom Message",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_software_update_app_update_enforce",
      "title" : "Enforce Software Update App Update Updates Automatically",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_software_update_download_enforce",
      "title" : "Enforce Software Update Downloads Updates Automatically",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_software_update_enforce",
      "title" : "Enforce Software Update Automatically",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_softwareupdate_current",
      "title" : "Ensure Software Update is Updated and Current",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_time_server_configure",
      "title" : "Configure macOS to Use an Authorized Time Server",
      "severity" : "medium"
    },
    {
      "id" : "system_settings_time_server_enforce",
      "title" : "Enforce macOS Time Synchronization",
      "severity" : "medium"
    },
    {
      "id" : "os_secure_enclave",
      "title" : "Protected Storage for Cryptographic Keys",
      "severity" : "medium"
    },
    {
      "id" : "audit_off_load_records",
      "title" : "Off-Load Audit Records",
      "severity" : "medium"
    },
    {
      "id" : "supplemental_filevault",
      "title" : "FileVault Supplemental",
      "severity" : "medium"
    }
  ]

  enabled_rules = {
    for rule in local.all_rules :
    rule.id => rule
    if !contains(var.disabled_rules, rule.id) && !contains(keys(var.exemptions), rule.id)
  }
}

# ---------------------------------------------------------------------------
# Device group — targets macOS 15 devices
# ---------------------------------------------------------------------------
resource "jamfplatform_device_group" "this" {
  name        = "${var.baseline_display_name} — macOS ${var.macos_version}"
  group_type  = "smart"
  device_type = "computer"
  criteria = [{
    criteria = "Operating System Version"
    operator = "greater than or equal"
    value    = var.macos_version_min
  }]
}

# ---------------------------------------------------------------------------
# Compliance Benchmark Engine — rule metadata from mSCP
# ---------------------------------------------------------------------------
data "jamfplatform_cbengine_rules" "this" {
  baseline_id = var.baseline_id
}

# ---------------------------------------------------------------------------
# Benchmark resource — all rules enabled by default, with per-rule overrides
# ---------------------------------------------------------------------------
resource "jamfplatform_cbengine_benchmark" "this" {
  title              = var.baseline_display_name
  description        = "${var.baseline_display_name} — mSCP ${var.mscp_branch} @ ${var.mscp_revision} — Managed by Terraform"
  source_baseline_id = var.baseline_id

  sources = [for s in data.jamfplatform_cbengine_rules.this.sources : {
    branch   = s.branch
    revision = s.revision
  }]

  rules = [
    for r in data.jamfplatform_cbengine_rules.this.rules : {
      id        = r.id
      enabled   = contains(keys(local.enabled_rules), r.id)
      odv_value = try(var.rule_overrides[r.id].odv_value, null)
    }
  ]

  target_device_group = jamfplatform_device_group.this.id
  enforcement_mode    = var.enforcement_mode
}
